-- TABLE SCHEMA FOR THE MUSIC BOT

CREATE TABLE IF NOT EXISTS GUILDS (
    ID BIGINT PRIMARY KEY,
    BOT_PREFIX VARCHAR(32) DEFAULT "p!",
    DJ_ROLE BIGINT DEFAULT 0,

    GUILD_BLACKLISTED BOOLEAN DEFAULT 0,
    GUILD_BLACKLISTED_REASON TEXT DEFAULT ""
);

CREATE TABLE IF NOT EXISTS USERS (
    ID BIGINT PRIMARY KEY,
    BLACKLISTED BOOLEAN DEFAULT 0,
    BLACKLISTED_REASON TEXT DEFAULT ""
);
